### ISSUE TITLE
Getting sailfish-qrshare into jolla store / harbour

### ISSUE THREAD

**Issue by ehdis** [monich/sailfish-qrshare#16]
I think the rpm scriptlet can be avoided? Any chance to get this app into the store? Thanks!

**Comment by monich** [comment]
No chance whatsoever. It's not just scriptlets, it's that it installs components in places where store apps are not allowed to install, and won't be allowed any time soon, if ever. And there's no way to uninstall it via UI which is yet another showstopper.

**Comment by ehdis** [comment]
Ok. Thanks for clarifying it.
