### ISSUE TITLE
Move mkicon to a separate repository?

### ISSUE THREAD

**Issue by martonmiklos** [monich/sailfish-qrshare#17]
Hi @monich !

While I have been blowing off the dust from my SMS share plugin I faced with issues of the icon size on the higher DPI screens. 

I have seen that you have implemented the generation of a PNG at RPM installation what I would like to leverage.
I would suggest to move the mkicon code to a separate repo so other plugins could use it as a submodule.
What do you think about this idea?

**Comment by monich** [comment]
Oh, this mkicon thing is so simple that I'm not sure that it would be worth the trouble. I would say it's fine to simply copy/paste it.

BTW I just noticed that dlopen stuff (if `HAVE_SILICA` is not defined) would have a problem on a 64-bit Sailfish OS (where 64-bit binaries get installed to `/usr/lib64`). Of course there's no 64-bit Sailfish OS yet, but there's a good chance that such thing will appear in not so distant future. I should fix that before I forget...

**Comment by martonmiklos** [comment]
Wah Sailfish 4.2 seems to be solved the icon size problems.
